cf_1:
  navigator:
    ros__parameters:
      navigator_plugins: ["navigate_to_pose_rrtx_static", "navigate_path_acmpc"]
      takeoff:
        altitude: 1.0
        position_tolerance: 0.05
        velocity_tolerance: 0.05
        update_frequency: 30.0 # Hz
      navigate_to_pose:
        planner: "rrtx_static"
        waypoint_position_tolerance: 0.1
        goal_position_tolerance: 0.1
        goal_velocity_tolerance: 0.1
        update_frequency: 100.0 # Hz
      navigate_path_acmpc:
        planner: "rrtx_static"
        waypoint_position_tolerance: 0.4
        goal_position_tolerance: 0.3
        goal_velocity_tolerance: 3.0
        update_frequency: 100.0 # Hz

planner_server:
  ros__parameters:
    planner_plugins: ["rrtx_static"]
    global_frame: "world"
    robot_base_frame: "base_link"
    rrtx_static:
      plugin: "rrtx_static_planner::RrtxStatic"
      obstacle_scaling: 2.0
      range: 0.0
      bounds_low:  [-0.5, -0.5, 0.9]
      bounds_high: [8.916, 3.950, 1.1]
      solve_time: 3.0 # Seconds

static_obstacle_advertiser:
  ros__parameters:
    global_frame: "world"
    obstacle_ids: ['1', '2', '3', '4', '5', '6',
                   '7', '8', '9', '10', '11', '12', '13', '14']
    obstacles_x: [
      -0.394,
      0.962,
      1.715,
      2.349,
      2.510,
      3.738,
      4.821,
      5.916,
      5.680,
      4.139,
      6.569,
      2.610,
      4.277,
      4.275
    ]
    obstacles_y: [
      2.50,
      3.327,
      3.435,
      3.528,
      -0.115,
      -0.146,
      -0.153,
      -0.027,
      2.090,
      3.854,
      3.544,
      1.656,
      1.101,
      0.474
    ]
    # obstacles_x: [ 1.524,
    #                2.1336,
    #                2.7432,
    #                3.3528,
    #                3.9624,
    #                3.9624,
    #                3.9624,
    #                3.9624,
    #                2.1336,
    #                2.1336,
    #                2.1336,
    #                2.1336,
    #                2.1336,
    #                1.524,
    #                0.9144,
    #                0.3048,
    #                0.3048,
    #                0.3048,
    #                0.3048,
    #                0.3048,
    #                0.3048]
    # obstacles_y: [ 0.3048,
    #                0.3048,
    #                0.3048,
    #                0.3048,
    #                0.9144,
    #                1.524,
    #                2.1336,
    #                2.7432,
    #                2.1336,
    #                2.7432,
    #                3.3528,
    #                3.9624,
    #                4.572,
    #                4.572,
    #                4.572,
    #                4.572,
    #                3.9624,
    #                3.3528,
    #                2.7432,
    #                2.1336,
    #                1.524]