static_obstacle_advertiser:
  ros__parameters:
    obstacle_ids: ['1', '2', '3', '4', '5', '6',
                   '7', '8', '9', '10', '11', '12',
                   '13', '14', '15', '16', '17', '18',
                   '19', '20', '21']
    obstacles_x: [ 1.524,
                   2.1336,
                   2.7432,
                   3.3528,
                   3.9624,
                   3.9624,
                   3.9624,
                   3.9624,
                   2.1336,
                   2.1336,
                   2.1336,
                   2.1336,
                   2.1336,
                   1.524,
                   0.9144,
                   0.3048,
                   0.3048,
                   0.3048,
                   0.3048,
                   0.3048,
                   0.3048]
    obstacles_y: [ 0.3048,
                   0.3048,
                   0.3048,
                   0.3048,
                   0.9144,
                   1.524,
                   2.1336,
                   2.7432,
                   2.1336,
                   2.7432,
                   3.3528,
                   3.9624,
                   4.572,
                   4.572,
                   4.572,
                   4.572,
                   3.9624,
                   3.3528,
                   2.7432,
                   2.1336,
                   1.524]