name: CI
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: nasa-uam-colcon/src/
          
      - name: Update Dependencies
        shell: bash
        working-directory: nasa-uam-colcon
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y libboost-all-dev qttools5-dev
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        shell: bash
        working-directory: nasa-uam-colcon
        run: |
          source /opt/ros/humble/setup.bash
          colcon build